#!/usr/bin/env php
<?php declare(strict_types=1);

use IKM\CLI\CommandLineFormatter;
use IKM\CLI\CommandLineWriter;

// Set folder
chdir(__DIR__);

// Error logging
ini_set('log_errors', '1');
ini_set('error_log', './php_errors.log');

// Autoload
require __DIR__ . '/vendor/autoload.php';

// Get CLI tools
$writer    = new CommandLineWriter();
$format = new CommandLineFormatter();


//$writer->hr();

$message = 'Astronomy-to-XYZ';
$writer->writeLine($message);

$writer->br();



// -------------
$output = 'Star Name, Ex: ' . $format->fg_bright_cyan . 'Alpha Centauri A' . $format->reset;
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$star_name = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Star Name: ';
    do{
        $input = readline($output);
    } while(empty($input));
}
$star_name = $input;
// -------------

$writer->br();



// -------------
$output = 'Right Ascension Hours, Ex: ' . $format->fg_bright_cyan . '14' . $format->reset . ' when ' . $format->fg_bright_cyan . '14' . $format->reset . 'h 39m 36.49400s';
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$right_ascension_hours = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Right Ascension Hours: ';
    do{
        $input = readline($output);
    } while(empty($input) && $input !== '0');
}
$right_ascension_hours = $input;
// -------------

// -------------
$output = 'Right Ascension Minutes, Ex: ' . $format->fg_bright_cyan . '39' . $format->reset . ' when 14h ' . $format->fg_bright_cyan . '39' . $format->reset . 'm 36.49400s';
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$right_ascension_minutes = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Right Ascension Minutes: ';
    do{
        $input = readline($output);
    } while(empty($input) && $input !== '0');
}
$right_ascension_minutes = $input;
// -------------

// -------------
$output = 'Right Ascension Seconds, Ex: ' . $format->fg_bright_cyan . '36.494' . $format->reset . ' when 14h 39m ' . $format->fg_bright_cyan . '36.49400' . $format->reset . 's';
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$right_ascension_seconds = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Right Ascension Seconds: ';
    do{
        $input = readline($output);
    } while(empty($input) && $input !== '0');
}
$right_ascension_seconds = $input;
// -------------

$writer->br();

// -------------
$output = 'Declination Degrees, Ex: ' . $format->fg_bright_cyan . '-60' . $format->reset . ' when ' . $format->fg_bright_cyan . '−60'. $format->reset .'° 50′ 02.3737″';
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$declination_degrees = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Declination Degrees: ';
    do{
        $input = readline($output);
    } while(empty($input) && $input !== '0');
}
$declination_degrees = $input;
// -------------

// -------------
$output = 'Declination Arcminutes, Ex: ' . $format->fg_bright_cyan . '50' . $format->reset . ' when −60° ' . $format->fg_bright_cyan . '50' . $format->reset . '′ 02.3737″';
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$declination_arcminutes = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Declination Arcminutes: ';
    do{
        $input = readline($output);
    } while(empty($input) && $input !== '0');
}
$declination_arcminutes = $input;
// -------------

// -------------
$output = 'Declination Arcseconds, Ex: ' . $format->fg_bright_cyan . '2.3737' . $format->reset . ' when −60° 50′ '. $format->fg_bright_cyan .'02.3737' . $format->reset . '″';
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$declination_arcseconds = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Declination Arcseconds: ';
    do{
        $input = readline($output);
    } while(empty($input) && $input !== '0');
}
$declination_arcseconds = $input;
// -------------

$writer->br();

// -------------
$output = 'Distance in Lightyears, Ex: ' . $format->fg_bright_cyan . '4.344' . $format->reset . ' when ' . $format->fg_bright_cyan . '4.344' . $format->reset . ' ± 0.002 ly';
fwrite(STDOUT, $output);

$is_ready = true;
$input = '';
$lightyears = '';
if($is_ready){
    fwrite(STDOUT, "\n");
    $output = $format->reset . 'Lightyears: ';
    do{
        $input = readline($output);
    } while(empty($input));
}
$lightyears = $input;
// -------------

$writer->br();

// --- RA conversion ---
//var ra_hours = ra_h + (ra_m / 60.0) + (ra_s / 3600.0)
//var ra = deg_to_rad(ra_hours * 15.0)

// Get inputs for Right Ascension
$given_right_ascension_hours_float = floatval($right_ascension_hours);
$given_right_ascension_minutes_float = floatval($right_ascension_minutes);
$given_right_ascension_seconds_float = floatval($right_ascension_seconds);

// Get Right Ascension as radians
$total_right_ascension_hours_float = $given_right_ascension_hours_float + ($given_right_ascension_minutes_float / 60.0) + ($given_right_ascension_seconds_float / 3600.0);
$right_ascension_degrees_float = $total_right_ascension_hours_float * 15.0;
$right_ascension_radians_float = deg2rad($right_ascension_degrees_float);

// --- Dec conversion ---
//var sign = 1.0
//if dec_deg < 0:
//    sign = -1.0
//
//var dec_total = abs(dec_deg) + (dec_m / 60.0) + (dec_s / 3600.0)
//var dec = deg_to_rad(dec_total * sign)

// Get inputs for Declination
$given_declination_degrees_float = floatval($declination_degrees);
$given_declination_arcminutes_float = floatval($declination_arcminutes);
$given_declination_arcseconds_float = floatval($declination_arcseconds);

// Get the sign from the first non-zero value of the Declination
$declination_sign = 1.0;
$is_sign_on_declination_degrees = false;
$is_sign_on_declination_arcminutes = false;
$is_sign_on_declination_arcseconds = false;
if (!empty($given_declination_degrees_float)) {
    $is_sign_on_declination_degrees = true;
    $is_declination_degrees_positive_or_zero = $given_declination_degrees_float >= 0.0;
    $declination_sign = ($is_declination_degrees_positive_or_zero) ? 1.0 : -1.0;
} elseif (!empty($given_declination_arcminutes_float)) {
    $is_sign_on_declination_arcminutes = true;
    $is_declination_arcminutes_positive_or_zero = $given_declination_arcminutes_float >= 0.0;
    $declination_sign = ($is_declination_arcminutes_positive_or_zero) ? 1.0 : -1.0;
} elseif (!empty($given_declination_arcseconds_float)) {
    $is_sign_on_declination_arcseconds = true;
    $is_declination_arcseconds_positive_or_zero = $given_declination_arcseconds_float >= 0.0;
    $declination_sign = ($is_declination_arcseconds_positive_or_zero) ? 1.0 : -1.0;
}

// Get Declination as radians
$unsigned_total_declination_degrees_float = abs($given_declination_degrees_float) + (abs($given_declination_arcminutes_float) / 60.0) + (abs($given_declination_arcseconds_float) / 3600.0);
$signed_total_declination_degrees_float = $unsigned_total_declination_degrees_float * $declination_sign;
$declination_radians_float = deg2rad($signed_total_declination_degrees_float);

// Get inputs for Distance
$distance_lightyears_float = abs(floatval($lightyears));

// --- Cartesian (Godot-friendly Y-up) ---
//var x = distance * cos(dec) * cos(ra)
//var y = distance * sin(dec)
//var z = distance * cos(dec) * sin(ra)
//
//return Vector3(x, y, z)

$z = ($distance_lightyears_float * cos($declination_radians_float) * cos($right_ascension_radians_float)) * -1.0;
$y = $distance_lightyears_float * sin($declination_radians_float);
$x = ($distance_lightyears_float * cos($declination_radians_float) * sin($right_ascension_radians_float)) * -1.0;

$cardinality_grid_up = null;
$cardinality_grid_down = null;
$cardinality_grid_left = null;
$cardinality_grid_right = null;
$cardinality_grid_forward = null;
$cardinality_grid_backward = null;

// Amount Up/Down
if($y > 0) {
    // Axis from the Earth's North Pole on the March Equinox
    $cardinality_grid_up = $y;
}
if($y < 0) {
    // Axis from the Earth's South Pole on the March Equinox
    $cardinality_grid_down = abs($y);
}

// Amount Left/Right
if($x > 0) {
    // Axis from the Earth's right-hand side (or starboard side) when facing the Sun on the March Equinox
    $cardinality_grid_right = $x;
}
if($x < 0) {
    // Axis from the Earth's left-hand side (or larboard/port side) when facing the Sun on the March Equinox
    $cardinality_grid_left = abs($x);
}

// Amount Forward/Backward
if($z > 0){
    // Axis from the center of the Earth pointed away the Sun on the March Equinox
    $cardinality_grid_backward = $z;
}
if($z < 0){
    // Axis pointed from the center of the Earth towards the center of the Sun on the March Equinox
    $cardinality_grid_forward = abs($z);
}

$writer->writeLine('Star: ' . $format->fg_bright_green . $star_name . $format->reset);
$writer->writeLine('Right Ascension: ' . $format->fg_bright_green . $right_ascension_hours . 'h ' . $right_ascension_minutes . 'm ' . $right_ascension_seconds . 's (' . $right_ascension_radians_float . 'rad)' . $format->reset);
$writer->writeLine('Declination: ' . $format->fg_bright_green . $declination_degrees . '° ' . $declination_arcminutes . '′ ' . $declination_arcseconds . '″ (' . $declination_radians_float .'rad)' . $format->reset);
$writer->writeLine('Distance: ' . $format->fg_bright_green . $lightyears . ' ly ' . $format->reset);

$writer->br();

//$x_nf = number_format($x, 4, '.', ',');
//$y_nf = number_format($y, 4, '.', ',');
//$z_nf = number_format($z, 4, '.', ',');

$writer->writeLine('XYZ: ' . $format->fg_bright_green . '(' . $x . ', ' . $y . ', ' . $z . ')' . $format->reset);

$writer->br();

if(!empty($cardinality_grid_up)) {
    $writer->writeLine($format->fg_bright_green . 'Up ' . $cardinality_grid_up . $format->reset);
}
if(!empty($cardinality_grid_down)) {
    $writer->writeLine($format->fg_bright_green . 'Down ' . $cardinality_grid_down . $format->reset);
}
if(!empty($cardinality_grid_forward)) {
    $writer->writeLine($format->fg_bright_green . 'Forward ' . $cardinality_grid_forward . $format->reset);
}
if(!empty($cardinality_grid_backward)) {
    $writer->writeLine($format->fg_bright_green . 'Backward ' . $cardinality_grid_backward . $format->reset);
}
if(!empty($cardinality_grid_left)) {
    $writer->writeLine($format->fg_bright_green . 'Left ' . $cardinality_grid_left . $format->reset);
}
if(!empty($cardinality_grid_right)) {
    $writer->writeLine($format->fg_bright_green . 'Right ' . $cardinality_grid_right . $format->reset);
}

$writer->br();

$location_is_on_origin                   =  empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_up_y_axis                = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_down_y_axis              =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_forward_z_axis           =  empty($cardinality_grid_up) &&  empty($cardinality_grid_down) && !empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_backward_z_axis          =  empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) && !empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_left_x_axis              =  empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) && !empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_right_x_axis             =  empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) && !empty($cardinality_grid_right);
$location_is_on_upper_face_yz_plane      = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) && !empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_upper_back_yz_plane      = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) && !empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_upper_left_xy_plane      = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) && !empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_upper_right_xy_plane     = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) && !empty($cardinality_grid_right);
$location_is_on_down_face_yz_plane       =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) && !empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_down_back_yz_plane       =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) && !empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_down_left_xy_plane       =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) && !empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_down_right_xy_plane      =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) && !empty($cardinality_grid_right);
$location_is_on_left_up_face_octant_1    = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) && !empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) && !empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_right_up_face_octant_2   = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) && !empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) && !empty($cardinality_grid_right);
$location_is_on_left_up_back_octant_3    = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) && !empty($cardinality_grid_backward) && !empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_right_up_back_octant_4   = !empty($cardinality_grid_up) &&  empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) && !empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) && !empty($cardinality_grid_right);
$location_is_on_left_down_face_octant_5  =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) && !empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) && !empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_right_down_face_octant_6 =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) && !empty($cardinality_grid_forward) &&  empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) && !empty($cardinality_grid_right);
$location_is_on_left_down_back_octant_7  =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) && !empty($cardinality_grid_backward) && !empty($cardinality_grid_left) &&  empty($cardinality_grid_right);
$location_is_on_right_down_back_octant_8 =  empty($cardinality_grid_up) && !empty($cardinality_grid_down) &&  empty($cardinality_grid_forward) && !empty($cardinality_grid_backward) &&  empty($cardinality_grid_left) && !empty($cardinality_grid_right);

if ($location_is_on_origin)                   {$writer->writeLine($format->fg_bright_green . 'Located on the origin'               . $format->reset);}
if ($location_is_on_up_y_axis)                {$writer->writeLine($format->fg_bright_green . 'Located on the Up Y-Axis'            . $format->reset);}
if ($location_is_on_down_y_axis)              {$writer->writeLine($format->fg_bright_green . 'Located on the Down Y-Axis'          . $format->reset);}
if ($location_is_on_forward_z_axis)           {$writer->writeLine($format->fg_bright_green . 'Located on the Front Z-Axis'         . $format->reset);}
if ($location_is_on_backward_z_axis)          {$writer->writeLine($format->fg_bright_green . 'Located on the Back Z-Axis'          . $format->reset);}
if ($location_is_on_left_x_axis)              {$writer->writeLine($format->fg_bright_green . 'Located on the Left X-Axis'          . $format->reset);}
if ($location_is_on_right_x_axis)             {$writer->writeLine($format->fg_bright_green . 'Located on the Right X-Axis'         . $format->reset);}
if ($location_is_on_upper_face_yz_plane)      {$writer->writeLine($format->fg_bright_green . 'Located on the Upper Front YZ-Plane' . $format->reset);}
if ($location_is_on_upper_back_yz_plane)      {$writer->writeLine($format->fg_bright_green . 'Located on the Upper Back YZ-Plane'  . $format->reset);}
if ($location_is_on_upper_left_xy_plane)      {$writer->writeLine($format->fg_bright_green . 'Located on the Upper Left XY-Plane'  . $format->reset);}
if ($location_is_on_upper_right_xy_plane)     {$writer->writeLine($format->fg_bright_green . 'Located on the Upper Right XY-Plane' . $format->reset);}
if ($location_is_on_down_face_yz_plane)       {$writer->writeLine($format->fg_bright_green . 'Located on the Lower Front YZ-Plane' . $format->reset);}
if ($location_is_on_down_back_yz_plane)       {$writer->writeLine($format->fg_bright_green . 'Located on the Lower Back YZ-Plane'  . $format->reset);}
if ($location_is_on_down_left_xy_plane)       {$writer->writeLine($format->fg_bright_green . 'Located on the Lower Left XY-Plane'  . $format->reset);}
if ($location_is_on_down_right_xy_plane)      {$writer->writeLine($format->fg_bright_green . 'Located on the Lower Right XY-Plane' . $format->reset);}
if ($location_is_on_left_up_face_octant_1)    {$writer->writeLine($format->fg_bright_green . 'Located in the Left Up-Face / Octant 1' . $format->reset);}
if ($location_is_on_right_up_face_octant_2)   {$writer->writeLine($format->fg_bright_green . 'Located in the Right Up-Face / Octant 2' . $format->reset);}
if ($location_is_on_left_up_back_octant_3)    {$writer->writeLine($format->fg_bright_green . 'Located in the Left Up-Back / Octant 3' . $format->reset);}
if ($location_is_on_right_up_back_octant_4)   {$writer->writeLine($format->fg_bright_green . 'Located in the Right Up-Back / Octant 4' . $format->reset);}
if ($location_is_on_left_down_face_octant_5)  {$writer->writeLine($format->fg_bright_green . 'Located in the Left Down-Face / Octant 5' . $format->reset);}
if ($location_is_on_right_down_face_octant_6) {$writer->writeLine($format->fg_bright_green . 'Located in the Right Down-Face / Octant 6' . $format->reset);}
if ($location_is_on_left_down_back_octant_7)  {$writer->writeLine($format->fg_bright_green . 'Located in the Left Down-Back / Octant 7' . $format->reset);}
if ($location_is_on_right_down_back_octant_8) {$writer->writeLine($format->fg_bright_green . 'Located in the Right Down-Back / Octant 8' . $format->reset);}



$writer->br();

// $writer->hr();